### ISSUE TITLE
undefined method `idname'でクラッシュする

### ISSUE THREAD

**Issue by Akkiesoft** [sora0920/mikutodon#19]
class MstdnUserでidnameが記述されていないので、Mastodonのトゥートが表示されるタイミングでクラッシュします。クラスの中で以下の宣言が必要です。

```
    def idname
      name
    end
```

確認したmikutodonのcommitは 1691a34de71e7f3310607499a10455a9e4470dfeです
mikutterの環境はhotfix/3.5、develop両方で確認しました。

### hotfix/3.5ブランチ

```
/Users/akkie/mikutter/core/plugin/user_detail_view/user_detail_view.rb:34:in `block (3 levels) in <top (required)>': undefined method `idname' for #<MstdnUser:0x007f917227d890> (NoMethodError)
Did you mean?  name
	from /Users/akkie/mikutter/core/plugin/user_detail_view/user_detail_view.rb:34:in `select'
	from /Users/akkie/mikutter/core/plugin/user_detail_view/user_detail_view.rb:34:in `block (2 levels) in <top (required)>'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/filter.rb:28:in `filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:59:in `block (2 levels) in filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `each'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `reduce'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `block in filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:57:in `catch'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:57:in `filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/plugin.rb:63:in `filtering'
	from /Users/akkie/mikutter/core/mui/gtk_timeline_utils.rb:84:in `add'
	from /Users/akkie/mikutter/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/akkie/mikutter/core/plugin/gtk/gtk.rb:260:in `block (2 levels) in <top (required)>'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	from /Users/akkie/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
	from /Users/akkie/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
	from /Users/akkie/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	from mikutter.rb:65:in `boot!'
	from mikutter.rb:94:in `<main>'
```

### developブランチ

```
/Users/akkie/mikutter/core/plugin/user_detail_view/user_detail_view.rb:34:in `block (3 levels) in <top (required)>': undefined method `idname' for #<MstdnUser:0x007ff445f42e28> (NoMethodError)
Did you mean?  name
	from /Users/akkie/mikutter/core/plugin/user_detail_view/user_detail_view.rb:34:in `select'
	from /Users/akkie/mikutter/core/plugin/user_detail_view/user_detail_view.rb:34:in `block (2 levels) in <top (required)>'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/filter.rb:28:in `filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:59:in `block (2 levels) in filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `each'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `reduce'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `block in filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:57:in `catch'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:57:in `filtering'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/plugin.rb:63:in `filtering'
	from /Users/akkie/mikutter/core/mui/gtk_timeline_utils.rb:84:in `add'
	from /Users/akkie/mikutter/core/lib/uithreadonly.rb:22:in `block (2 levels) in singleton class'
	from /Users/akkie/mikutter/core/plugin/gtk/gtk.rb:261:in `block (2 levels) in <top (required)>'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	from /Users/akkie/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	from /Users/akkie/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
	from /Users/akkie/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
	from /Users/akkie/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	from mikutter.rb:68:in `boot!'
	from mikutter.rb:104:in `<main>'
```

**Comment by sora0920** [comment]
修正しました。こちら側ではエラーがでないので確認お願いします。

**Comment by toshia** [comment]
多分これは、Twitterユーザのプロフィールを開いてる状態でtootを受信しないと再現しないですね。
mikutterとしてはidnameフィールドをMessageに要求するのはやめたいと考えているのでこれでクラッシュするのはmikutterのバグです。

しかし現実的には、今までTwitterのために作られたサードパーティプラグインはidnameフィールドを仮定していて、意味合いから言ってもその依存度は他のフィールドより強いので、他のサードパーティプラグインで同様の問題が起こることは多いはずです。実装しておいたほうが良いと思います。

**Comment by Akkiesoft** [comment]
クラッシュしなくなることを確認できました。

> 多分これは、Twitterユーザのプロフィールを開いてる状態でtootを受信しないと再現しないですね。

user_detail_viewで置きているのは気づいていたのでそこは確認したのですが、ユーザのプロフィールは開かれていなくて、ふむ……？となっているところです。
# この先はmikutter Redmineで別途チケット作成になるかも

**Comment by toshia** [comment]
mikutter側のチケットは作成しておきます。

**Comment by sora0920** [comment]
このissueは対応完了でOKですかね？

**Comment by Akkiesoft** [comment]
良いと思いますー。

**Comment by sora0920** [comment]
了解です。
